-- AlterTable
ALTER TABLE `Event` ADD COLUMN `heroText` TEXT NULL,
    ADD COLUMN `heroTitel` VARCHAR(191) NULL,
    ADD COLUMN `theme` ENUM('STANDARD', 'BUSINESS', 'PREMIUM') NOT NULL DEFAULT 'STANDARD';
