-- AlterTable
ALTER TABLE `Registration` ADD COLUMN `reserviertBis` DATETIME(3) NULL,
    MODIFY `status` ENUM('RESERVIERT', 'BESTAETIGT', 'WARTELISTE', 'STORNIERT') NOT NULL DEFAULT 'BESTAETIGT';

-- CreateTable
CREATE TABLE `ZahlungsEreignis` (
    `id` VARCHAR(191) NOT NULL,
    `art` VARCHAR(191) NOT NULL,
    `empfangenAm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
