-- AlterTable
ALTER TABLE `Checkliste` MODIFY `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'CHECKLISTE';

-- AlterTable
ALTER TABLE `Loeschprotokoll` MODIFY `klasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL;

-- AlterTable
ALTER TABLE `Registration` MODIFY `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'ANMELDEDATEN';

-- AlterTable
ALTER TABLE `Vorfall` MODIFY `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'VORFALLAKTE';

-- AlterTable
ALTER TABLE `Zustimmungsnachweis` MODIFY `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'ZUSTIMMUNGSNACHWEIS';

-- CreateTable
CREATE TABLE `Aufnahmewiderspruch` (
    `id` VARCHAR(191) NOT NULL,
    `eventId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `registrationId` VARCHAR(191) NULL,
    `weg` ENUM('CHECKIN', 'VOR_ORT', 'EMAIL', 'SONSTIGES') NOT NULL DEFAULT 'VOR_ORT',
    `notiz` TEXT NULL,
    `erklaertAm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `erfasstVon` VARCHAR(191) NOT NULL,
    `zurueckgenommenAm` DATETIME(3) NULL,
    `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'AUFNAHMEWIDERSPRUCH',
    `faelligAm` DATETIME(3) NULL,

    INDEX `Aufnahmewiderspruch_eventId_zurueckgenommenAm_idx`(`eventId`, `zurueckgenommenAm`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Veroeffentlichungspruefung` (
    `id` VARCHAR(191) NOT NULL,
    `eventId` VARCHAR(191) NOT NULL,
    `ziel` VARCHAR(191) NOT NULL,
    `widersprueche` INTEGER NOT NULL,
    `namen` TEXT NULL,
    `erkennbar` BOOLEAN NOT NULL DEFAULT false,
    `notiz` TEXT NULL,
    `geprueftAm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geprueftVon` VARCHAR(191) NOT NULL,
    `loeschklasse` ENUM('GESUNDHEITSANGABEN', 'EINVERSTAENDNIS_VOLL', 'ZUSTIMMUNGSNACHWEIS', 'ANMELDEDATEN', 'CHECKLISTE', 'VORFALLAKTE', 'STEUERUNTERLAGEN', 'AUFNAHMEWIDERSPRUCH') NOT NULL DEFAULT 'AUFNAHMEWIDERSPRUCH',
    `faelligAm` DATETIME(3) NULL,

    INDEX `Veroeffentlichungspruefung_eventId_geprueftAm_idx`(`eventId`, `geprueftAm`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Aufnahmewiderspruch` ADD CONSTRAINT `Aufnahmewiderspruch_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Aufnahmewiderspruch` ADD CONSTRAINT `Aufnahmewiderspruch_registrationId_fkey` FOREIGN KEY (`registrationId`) REFERENCES `Registration`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Veroeffentlichungspruefung` ADD CONSTRAINT `Veroeffentlichungspruefung_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
